; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -O3 -S | FileCheck %s
; IR generated for a function containing the loop:
;   #pragma clang loop ivdep(enable)
;   for (int i=0; i<LEN_1D; i++)
;     a[b[i]]++
; where LEN_1D is an integer constant.
; The above is an unknown dependency as the vectorizer cannot determine if
; vectorizing accesses to a[b[i]] will be safe or unsafe.
; Check if loop has been vectorized when ivdep is present.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: noinline nounwind uwtable
define dso_local i32* @addLoops(i32* noalias %a, i32* noalias %b, i32 %LEN_1D) #0 {
; CHECK-LABEL: define dso_local ptr @addLoops
; CHECK-SAME: (ptr noalias returned captures(ret: address, provenance) [[A:%.*]], ptr noalias readonly captures(none) [[B:%.*]], i32 [[LEN_1D:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK:       for.body.preheader:
; CHECK:       vector.ph:
; CHECK:       vector.body:
; CHECK:       middle.block:
; CHECK:       for.body.preheader7:
; CHECK:       for.body:
; CHECK:       for.end:
; CHECK-NEXT:    ret ptr [[A]]
;

entry:
  %a.addr = alloca i32*, align 8
  %b.addr = alloca i32*, align 8
  %LEN_1D.addr = alloca i32, align 4
  %i = alloca i32, align 4
  store i32* %a, i32** %a.addr, align 8
  store i32* %b, i32** %b.addr, align 8
  store i32 %LEN_1D, i32* %LEN_1D.addr, align 4
  store i32 0, i32* %i, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load i32, i32* %i, align 4
  %1 = load i32, i32* %LEN_1D.addr, align 4
  %cmp = icmp slt i32 %0, %1
  br i1 %cmp, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %2 = load i32*, i32** %a.addr, align 8
  %3 = load i32*, i32** %b.addr, align 8
  %4 = load i32, i32* %i, align 4
  %idxprom = sext i32 %4 to i64
  %arrayidx = getelementptr inbounds i32, i32* %3, i64 %idxprom
  %5 = load i32, i32* %arrayidx, align 4
  %idxprom1 = sext i32 %5 to i64
  %arrayidx2 = getelementptr inbounds i32, i32* %2, i64 %idxprom1
  %6 = load i32, i32* %arrayidx2, align 4
  %inc = add nsw i32 %6, 1
  store i32 %inc, i32* %arrayidx2, align 4
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %7 = load i32, i32* %i, align 4
  %inc3 = add nsw i32 %7, 1
  store i32 %inc3, i32* %i, align 4
  br label %for.cond, !llvm.loop !2

for.end:                                          ; preds = %for.cond
  %8 = load i32*, i32** %a.addr, align 8
  ret i32* %8
}

attributes #0 = { noinline nounwind uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0 (https://github.com/llvm/llvm-project 8a5bfbe6db2824642bf9a1d27a24c5b6132b244f)"}
; CHECK: !2 = distinct !{!2, !3, !4}
; CHECK-NEXT: !3 = !{!"llvm.loop.isvectorized", i32 1}
; CHECK-NEXT: !4 = !{!"llvm.loop.unroll.runtime.disable"}
!2 = distinct !{!2, !3, !4}
!3 = !{!"llvm.loop.vectorize.ivdep.enable", i1 true}
!4 = !{!"llvm.loop.vectorize.enable", i1 true}
