// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -O3 -o - %s | FileCheck %s

// CHECK-LABEL: define dso_local void @ivdep_demo1(
// CHECK-SAME: ptr noundef captures(none) [[A:%.*]], i32 noundef [[K:%.*]], i32 noundef [[C:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK:       for.body.preheader:
// CHECK:       vector.ph:
// CHECK:       vector.body:
// CHECK:       middle.block:
// CHECK:       for.body.preheader12
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    ret void
// CHECK:       for.body:
//
void ivdep_demo1 (int *a, int k, int c, int m) {
#pragma clang loop ivdep(enable)
    for (int i = 0; i < m; i++)
	a[i] = a[i + k] * c;
}

// CHECK-LABEL: define dso_local void @ivdep_demo2(
// CHECK-SAME: ptr noundef captures(none) [[E:%.*]], ptr noundef readonly captures(none) [[IX:%.*]], i32 noundef [[I:%.*]], i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK:       for.body.lr.ph:
// CHECK:       vector.ph:
// CHECK:       vector.body:
// CHECK:       middle.block:
// CHECK:       for.body.preheader:
// CHECK:       for.body:
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void ivdep_demo2 (int *e, int ** ix, int i, int n) {
#pragma clang loop ivdep(enable)
    for (i=1; i<n; i++) {
	e[ix[2][i]] = e[ix[2][i]]+1.0;
	e[ix[3][i]] = e[ix[3][i]]+2.0;
    }
}

// CHECK-LABEL: define dso_local void @ivdep_demo3(
// CHECK-SAME: ptr noundef captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]], i32 noundef [[J:%.*]], i32 noundef [[N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK:       for.body.preheader:
// CHECK:       vector.ph:
// CHECK:       vector.body:
// CHECK:       middle.block:
// CHECK:       for.body:
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void ivdep_demo3 (int * a, int * b, int j, int n) {
#pragma clang loop ivdep(enable)
    for (j=0; j<n; j++)
    {
	a[b[j]] = a[b[j]] + 1;
    }
}

// CHECK-LABEL: define dso_local void @ivdep_demo4(
// CHECK-SAME: ptr noundef captures(none) [[A:%.*]], ptr noundef captures(none) [[B:%.*]], i32 noundef [[K:%.*]], i32 noundef [[C:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK:       for.body.preheader:
// CHECK:       vector.memcheck:
// CHECK:       vector.ph:
// CHECK:       vector.body:
// CHECK:       middle.block:
// CHECK:       for.body.preheader29:
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    ret void
// CHECK:       for.body:
//
void ivdep_demo4 (int *a, int *b, int k, int c, int m) {
#pragma clang loop ivdep(enable)
    for (int i = 0; i < m; i++) {
	a[i] = a[i + m] * c;
	b[i] = b[i + m] * c;
    }
}

// CHECK-LABEL: define dso_local void @ivdep_demo5(
// CHECK-SAME: ptr noundef captures(none) [[A:%.*]], ptr noundef readnone captures(none) [[B:%.*]], ptr noundef readnone captures(none) [[C:%.*]], i32 noundef [[M:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK:       for.body.preheader:
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    ret void
// CHECK:       for.body:
//
void ivdep_demo5 (int *a, int *b, int *c, int m) {
#pragma clang loop ivdep(enable)
    for (int i = 0; i < m; i++) {
	a[i] = a[i + 1] + a[i - 1];
    }
}
//.
// CHECK: !7 = !{!"llvm.loop.mustprogress"}
// CHECK: !8 = !{!"llvm.loop.isvectorized", i32 1}
// CHECK: !9 = !{!"llvm.loop.unroll.runtime.disable"}
// CHECK: !10 = distinct !{!10, !7, !9, !8}
// CHECK: !20 = distinct !{!20, !7, !21, !22}
// CHECK: !21 = !{!"llvm.loop.vectorize.ivdep.enable", i1 true}
// CHECK: !22 = !{!"llvm.loop.vectorize.enable", i1 true}
//.
